INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Nội Dung',0,1,'','','',1,'noi-dung',1,1,'{\"t\":1,\"oi\":0}','icon-file-text-alt',[now],[now],[user_id]);
set @menus_admin1 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý tin tức',@menus_admin1,1,'','content/news/index','[]',1,'quan-ly-tin-tuc',1,1,'{\"t\":5,\"oi\":\"news.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin2 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Danh mục tin tức',@menus_admin1,1,'','content/newscategory/index','[]',2,'danh-muc-tin-tuc',1,1,'{\"t\":5,\"oi\":\"newscategory.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin3 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý trang nội dung',@menus_admin1,1,'','content/categorypage/index','[]',3,'quan-ly-trang-noi-dung',1,1,'{\"t\":5,\"oi\":\"categorypage.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin4 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Sản phẩm',0,1,'','','',2,'san-pham',1,1,'{\"t\":1,\"oi\":0}','icon-file',[now],[now],[user_id]);
set @menus_admin5 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý sản phẩm',@menus_admin5,1,'','economy/product/index','[]',1,'quan-ly-san-pham',1,1,'{\"t\":5,\"oi\":\"product.index\"}','icon-file',[now],[now],[user_id]);
set @menus_admin6 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Danh mục sản phẩm',@menus_admin5,1,'','economy/productcategory/index','[]',2,'danh-muc-san-pham',1,1,'{\"t\":5,\"oi\":\"productcategory.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin7 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Đăng sản phẩm',@menus_admin5,1,'','economy/product/index','[]',3,'dang-san-pham',1,1,'{\"t\":5,\"oi\":\"product.create\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin8 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Banner',0,1,'','','',3,'banner',1,1,'{\"t\":1,\"oi\":0}','icon-building',[now],[now],[user_id]);
set @menus_admin9 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý banner',@menus_admin9,1,'','banner/banner/index','[]',1,'quan-ly-banner',1,1,'{\"t\":5,\"oi\":\"banner.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin10 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý nhóm banner',@menus_admin9,1,'','banner/bannergroup/index','[]',2,'quan-ly-nhom-banner',1,1,'{\"t\":5,\"oi\":\"bannergroup.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin11 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Thư viện ảnh',0,1,'','','',4,'thu-vien-anh',1,1,'{\"t\":1,\"oi\":0}','icon-picture',[now],[now],[user_id]);
set @menus_admin12 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý album',@menus_admin12,1,'','media/album/index','[]',1,'quan-ly-album',1,1,'{\"t\":5,\"oi\":\"album.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin13 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Giao diện',0,1,'','','',5,'giao-dien',1,1,'{\"t\":1,\"oi\":0}','icon-desktop',[now],[now],[user_id]);
set @menus_admin14 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý menu',@menus_admin14,1,'','interface/menugroup/index','[]',1,'quan-ly-menu',1,1,'{\"t\":5,\"oi\":\"menugroup.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin15 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Chân trang(footer)',@menus_admin14,1,'','interface/sitesettings/footersetting','[]',2,'chan-trangfooter',1,1,'{\"t\":5,\"oi\":\"sitesettings.footersetting\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin16 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Thông tin liên hệ',@menus_admin14,1,'','interface/sitesettings/contact','[]',3,'thong-tin-lien-he',1,1,'{\"t\":5,\"oi\":\"sitesettings.contact\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin17 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Cấu hình',0,1,'','','',6,'cau-hinh',1,1,'{\"t\":1,\"oi\":0}','icon-cogs',[now],[now],[user_id]);
set @menus_admin18 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Cấu hình website',@menus_admin18,1,'','setting/setting/index','[]',1,'cau-hinh-website',1,1,'{\"t\":5,\"oi\":\"setting.index\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin19 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Quản lý tên miền',@menus_admin18,1,'','setting/setting/domainsetting','[]',2,'quan-ly-ten-mien',1,1,'{\"t\":5,\"oi\":\"setting.domainsetting\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin20 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Khách hàng',0,1,'','','',7,'khach-hang',1,1,'{\"t\":1,\"oi\":0}','icon-group',[now],[now],[user_id]);
set @menus_admin21 = LAST_INSERT_ID();
INSERT INTO menus_admin (menu_id, site_id, user_id, menu_title, parent_id, menu_linkto, menu_link, menu_basepath, menu_pathparams, menu_order, alias, status, menu_target, menu_values, iconclass, created_time, modified_time, modified_by) VALUES (null,[site_id],[user_id],'Liên hệ',@menus_admin21,1,'','custom/customform/statistic','[]',1,'lien-he',1,1,'{\"t\":5,\"oi\":\"customform.statistic\"}','icon-double-angle-right',[now],[now],[user_id]);
set @menus_admin22 = LAST_INSERT_ID();