<?php $this->renderPartial('partial/warranty_menu') ?>
<div class="col-md-9 htmlpage-content">
    <h1 style="margin-top: -18px;   margin-bottom: 10px;">Các trường hợp không được áp dụng bảo hành</h1>
    <p style="text-align: justify;"><strong>Điều kiện bảo hành sẽ không được áp dụng cho:</strong></p>
    <p style="text-align: justify;"><br>1. Bất cứ một hư hỏng nào xảy ra do việc không tiến hành bảo dưỡng định kỳ, bảo quản xe hay vận chuyển xe không đúng quy cách.</p>
    <p style="text-align: justify;"><br>2. Bất cứ một hư hỏng nào xảy ra do việc sửa chữa hay bảo dưỡng không tuân theo các phương pháp như chỉ dẫn của Công ty Cổ phần Ô tô Hyundai Thành Công Việt Nam và bất cứ hư hỏng nào là nguyên nhân của việc sửa chữa, điều chỉnh không phải do Đại lý ủy nhiệm tiến hành.</p>
    <p style="text-align: justify;"><br>3. Bất cứ một hư hỏng nào xảy ra do xe làm việc quá tải, lái xe trên địa hình không phù hợp hay vận hành xe không theo các phương pháp được chỉ ra trong sách hướng dẫn sử dụng hay vượt quá giới hạn quy định (tải trọng tối đa, số lượng hành khách, tốc độ động cơ và các đặc điểm khác).</p>
    <p style="text-align: justify;"><br>4. Bất cứ một hư hỏng nào xảy ra do việc sử dụng các phụ tùng, các loại dầu và hóa chất hay các phụ kiện không chính hiệu. Việc sử dụng các phụ tùng, các loại dầu và hóa chất hay các phụ kiện không chính hiệu có thể làm giảm khả năng hoạt động và độ tin cậy của xe. Công ty Cổ phần Ô tô Hyundai Thành Công Việt Nam sẽ không chịu trách nhiệm về các chi phí liên quan đến các phụ tùng bị hư hỏng do việc sử dụng các nhiên liệu, các chất bôi trơn hay các hóa chất (dầu, dầu phanh, nước làm mát và các loại khác) không chính hiệu.</p>
    <p style="text-align: justify;"><br>5. Bất cứ một hư hỏng nào xảy ra do những sửa đổi mà không được Công ty Cổ phần Ô tô Hyundai Thành Công Việt Nam phê duyệt.</p>
    <p style="text-align: justify;"><br>6. Các hiện tượng như tiếng ồn, độ rung, thấm dầu, ăn mòn hay giảm giá trị tự nhiên mà không ảnh hưởng tới chất lượng sản phẩm, chức năng và hiệu suất làm việc của xe.</p>
    <p style="text-align: justify;"><br>7. Các phụ tùng hao mòn do sử dụng như bu-gi, các bộ lọc nhiên liệu, các bộ lọc dầu, các bộ lọc gió, má phanh, đĩa ly hợp, đèn, cầu chì, chổi than, cần gạt nước, dây đai, lốp xe và các bộ phận bằng cao su, kính và các danh mục phụ tùng khác do Công ty Cổ phần Ô tô Hyundai Thành Công Việt Nam quy định.</p>
    <p style="text-align: justify;"><br>8. Các dung dịch như dầu, mỡ, dung dịch điện phân cho ắc quy, nước làm mát, bộ tản nhiệt và các danh mục khác do Công ty Cổ phần Ô tô Hyundai Thành Công Việt Nam quy định.</p>
    <p style="text-align: justify;"><br>9. L àm sạch, kiểm tra, điều chỉnh và các hạng mục bảo dưỡng định kỳ khác. Các chi phí phát sinh cho việc kiểm tra định kỳ xe ô tô do Đại lý thực hiện sẽ không nằm trong trách nhiệm bảo hành của Công ty Cổ phần Ô tô Hyundai Thành Công Việt Nam.</p>
    <p style="text-align: justify;"><br>10. Bất cứ một khoản chi phí nào để khắc phục hậu quả của việc sửa chữa bảo dưỡng không đúng đã được thực hiện trước đó. Chi phí sữa chữa này sẽ do Đại lý ủy nhiệm – nơi tiến hành công việc sửa chữa sai đó – chi trả, kể cả khi thời gian bảo hành đã ký hết. Khách hàng sẽ không phải trả tiền cho những công việc này.</p>
    <p style="text-align: justify;"><span>11. Bất cứ hư hỏng nào gây ra bởi các yếu tố ngoài tầm kiểm soát của nhà sản xuất như thảm họa tự nhiên, cháy nổ, va chạm, đá văng, trộm cắp và các hư hỏng xảy ra sau đó do hậu quả của các sự kiện này, hư hỏng nào gây ra bởi khói, các chất hóa học, phân chim, nước biển, gió biển, mưa axít hay các hiện tượng tương tự khác.</span></p>                
</div>